version: '3.7'
services:
  mongodb:
    image: mongo:6
    container_name: mongodb-4rn
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=12345
      - ME_CONFIG_MONGODB_URL=mongodb://root:12345@mongodb-4rn:27017/admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always

volumes:
  mongodb_data:

  #docker compose -p tuanstark-mongodb-4rn up -d
  #docker compose -p tuanstark-mongodb-4rn down
